version: 2.1

orbs:
  notification: ./src/@orb.yml

workflows:
  test:
    jobs:
      - notification/notify_success:
          channel: "#test"
          message: "Test success message"
      - notification/notify_custom:
          channel: "#test"
          message: "Test custom message"
          status: "info"
