version: 2.1

description: >
  A simple and reusable Slack notification orb for CircleCI. Provides easy-to-use
  commands and jobs for sending notifications to your team with customizable
  messages and build status using the official CircleCI Slack orb.

display:
  home_url: "https://github.com/UnMars/slack-orb-demo"
  source_url: "https://github.com/UnMars/slack-orb-demo"

orbs:
  slack: circleci/slack@5.2.3

executors:
  default:
    docker:
      - image: cimg/base:current

commands:
  notify:
    description: "Send a notification to Slack"
    parameters:
      channel:
        type: string
        description: "Slack channel to send message to"
        default: $SLACK_DEFAULT_CHANNEL
      message:
        type: string
        description: "Message to send"
        default: "Notification from CircleCI"
    steps:
      - slack/notify:
          event: always
          channel: << parameters.channel >>
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@U09DLG4ECRM> << parameters.message >>"
                  }
                }
              ]
            }

jobs:
  notify:
    description: "Job to send notifications to Slack"
    parameters:
      channel:
        type: string
        description: "Slack channel to send message to"
        default: $SLACK_DEFAULT_CHANNEL
      message:
        type: string
        description: "Message to send"
        default: "Notification from CircleCI"
    executor: default
    steps:
      - checkout
      - notify:
          channel: << parameters.channel >>
          message: << parameters.message >>
